# New problem: You have the option of picking one of two games to play.
# Setup: You observe a uniformly random sequence of zeros and ones generated by a computer. This is like flipping a coin and generating 0 if the outcome is heads and 1 if the outcome is tails. Assume the coin is unbiased. The sequence stops after 'n' trials. (edited)
# Game #1: If you observe the sub-sequence '10', you get a point. For example, if n=5 and the observed sequence is 10110, you get 2 points.
# Game #2: If you observe the sub-sequence '11', you get a point. For example, if n=6 and the observed sequence is 101110, you get 1 point. Note that you cannot count any digit towards two separate sub-sequences - if you see 1111, it counts as 2 points and not 3.
# Which game would you play and why?


ascores=c()
bscores=c()
bscoresOverlap=c()
testLen = 100

for (j in 1:testLen) {

n=10000
flips = sample(c(0,1),n, replace=TRUE)

ascore = 0
for (i in 2:n) if(flips[i]==0 && flips[i-1]==1) ascore = ascore+1
ascores=append(ascores, ascore)

bscore = 0
if(flips[1]+flips[2]==2) bscore=1
for (i in 3:n) if (flips[i]==1 && flips[i-1]==1 && flips[i-2]==0) bscore = bscore+1
bscores=append(bscores, bscore)

bscoreOverlap =0 
for (i in 2:n) if(flips[i]==1 && flips[i-1]==1) bscoreOverlap = bscoreOverlap+1
bscoresOverlap=append(bscoresOverlap, bscoreOverlap)
}

am=mean(ascores)
bm=mean(bscores)
bom=mean(bscoresOverlap)

as=sd(ascores)
bs=sd(bscores)
bos=sd(bscoresOverlap)